version: "3.8"

services:
  fastify-graphql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ryan
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
